<?php
// $Id$

/**
 * @file
 *  This module provides integration with the git versioning system.
 */

/**
 * Implementation of hook_autoload_info().
 */
function dpgit_autoload_info() {
  return array(
    'DPGitPackager' => array('file' => 'includes/DPGitPackager.class.inc'),
  );
}

/**
 * Implementation of hook_dproject_api().
 *
 * @return void
 */
function dpgit_dproject_api() {
  return array(
    '1' => array(
      'path' => drupal_get_path('module', 'dpgit') . '/includes',
      'packagers' => array(
        'git' => array(
          'name' => t('Git repository'),
          'class' => 'DPGitPackager',
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function dpgit_theme() {
  return array(
    'git_log' => array(
      'file' => 'includes/dpgit.inc',
      'function' => '_dpgit_theme_log',
      'arguments' => array('log' => array()),
    ),
    'git_log_item' => array(
      'file' => 'includes/dpgit.inc',
      'function' => '_dpgit_theme_log_item',
      'arguments' => array('sha1' => '', 'item' => array()),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function dpgit_menu() {
  $items = array();

  $items['admin/settings/dproject/git'] = array(
    'title' => 'Git settings',
    'description' => 'Configuration options for dproject git integration',
    'page callback' => 'drupal_get_form',
    'file' => 'includes/dpgit.inc',
    'page arguments' => array('_dpgit_settings'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

