<?php
// $Id$

define('DPGIT_DPROJECT_NAMESPACE', 'http://goodold.se/project/dproject/dpgit');

function dpgit_dproject_packager() {
  return array(
    'git' => array(
      'title' => t('Git'),
      'namespace' => DPGIT_DPROJECT_NAMESPACE,
      'configuration form' => '_dpgit_configure_source', 
      'configuration submit' => '_dpgit_configure_source_submit',
      'update' => '_dpgit_fetch',
      'package' => '_dpgit_package',
      'configure release' => '_dpgit_configure_release',
      'packager description' => '_dpgit_description',
      'reference description' => '_dpgit_reference_description',
      'packager created' => '_dpgit_created',
      'packager deleted' => '_dpgit_deleted',
      'sources' => array(
        'branches' => array(
          'title' => 'Branches',
          'options' => '_dpgit_branches_options',
          'resolve' => '_dpgit_ref_sha1',
        ),
        'tags' => array(
          'title' => 'Tags',
          'options' => '_dpgit_tags_options',
          'resolve' => '_dpgit_ref_sha1',
        ),
        'recent_commits' => array(
          'title' => 'Recent commits',
          'options' => '_dpgit_recent_commits',
          'resolve' => '_dpgit_ref_sha1',
        ),
      ),
    ),
  );
}

function dpgit_theme() {
  return array(
    'git_log' => array(
      'function' => '_dpgit_theme_log',
      'arguments' => array('log' => array()),
    ),
  );
}

/**
 * Configures a release object using the supplied information
 *
 * @param DProjectRelease $release 
 *  The release object to configure
 * @param stdClass $packager 
 *  The packager object
 * @param string $reference 
 *  The reference that was used (tag, branch, sha1 and so on)
 * @param string $sha1 
 *  The sha1 that the reference has been resolved to
 * @return void
 */
function _dpgit_configure_release(&$release, $packager, $reference, $sha1) {
  $config = array(
    'sha1' => $sha1,
    'origin' => $packager->configuration->url,
  );
  
  if ($reference != $sha1) {
    $config['reference'] = $reference;
  }
  
  $release->set_metadata('git', DPGIT_DPROJECT_NAMESPACE, (object)$config);
}

/**
 * Deletes the local git repositiory
 *
 * @param stdClass $packager
 *  The packager object
 * @return void
 */
function _dpgit_deleted($packager) {
  $wdir = dproject_working_directory_path($packager);
  if (file_exists(dirname($wdir))) {
    exec('rm -fr "' . $wdir . '"');
  }
}

/**
 * Creates a local clone of the git repository
 *
 * @param stdClass $packager
 *  The packager object
 * @return void
 */
function _dpgit_created($packager, &$status_out=Null) {
  $wdir = dproject_working_directory_path($packager);
  if (file_exists(dirname($wdir)) || mkdir(dirname($wdir), 0777, TRUE)) {
    // Make sure that the working dir doesn't exist (by killing it if it does)
    if (file_exists($wdir)) {
      dproject_delete_directory($wdir);
    }

    $out = array();
    $return = 0;
    $cmd = 'git clone "' . $packager->configuration->url . '" "' . $wdir . '"';
    exec($cmd, $out, $return);

    if ($return === 0) {
      drupal_set_message(t('Git: Initialized empty Git repository in !dir', array('!dir' => $wdir)));
      if ($status_out) {
        $status_out = join($out, '<br/>');
      }
    }
    else {
      dproject_set_packager_message($packager, 'dpgit', 'clone', 'Git: Failed to clone !url to !dir:<br/>@out', array(
        '!url' => $packager->configuration->url,
        '!dir' => $wdir,
        '@out' => join($out, '<br/>'),
      ), WATCHDOG_ERROR);
    }

    // Return command output if we got a $status_out reference
    if ($status_out) {
      $status_out = join($out, '<br/>');
    }
    return ($return === 0);
  }
  else {
    // Let people know if we couldn't prepare a parent directory for the working dir
    dproject_set_packager_message($packager, 'dpgit', 'clone', 'Git: Failed to create working directory, the parent directory !dir does not exist and could not be created', array(
      '!dir' => dirname($wdir),
    ), WATCHDOG_ERROR);
  }
}

function _dpgit_fetch($packager, &$status_out=NULL) {
  $wdir = dproject_working_directory_path($packager);
  if (file_exists($wdir)) {
    $out = array();
    $return = 0;
    $cmd = 'git --git-dir="' . $wdir . '/.git" fetch origin';
    exec($cmd, $out, $return);

    if ($return === 0) {
      drupal_set_message(t('Git: Fetched updates from !url', array('!url' => $packager->configuration->url)));
    }
    else {
      dproject_set_packager_message($packager, 'dpgit', 'fetch', 'Git: Failed to fetch updates from !url to !dir:<br/>@out', array(
        '!url' => $packager->configuration->url,
        '!dir' => $wdir,
        '@out' => join($out, '<br/>'),
      ), WATCHDOG_ERROR);
    }

    // Return command output if we got a $status_out reference
    if (is_string($status_out)) {
      $status_out = join($out, '<br/>');
    }
    return ($return === 0);
  }
  else {
    dproject_set_packager_message($packager, 'dpgit', 'fetch', 'Git: The working directort !dir doesn\'t exist', array(
      '!dir' => $wdir,
    ), WATCHDOG_ERROR);
    return FALSE;
  }
}

/**
 * Callback for generating a form fragment for configuring
 * a new git packager.
 *
 * @return array
 *  A form fragment
 */
function _dpgit_configure_source() {
  $form = array();
  $form['git_source'] = array(
    '#type' => 'textfield',
    '#required' => TRUE,
    '#title' => t('The url or path to the git repository'),
  );
  return $form;
}

/**
 * Callback for turning the submitted values for _dpgit_configure_source
 * into a configuration array
 *
 * @param string $values
 * @return array
 *  A configuration array
 */
function _dpgit_configure_source_submit($values) {
  return array(
    'url' => $values['git_source'],
  );
}

/**
 * Callback for getting a description for a git packager
 *
 * @param stdClass $packager
 *  A packager object
 * @return string
 *  A description
 */
function _dpgit_description($packager) {
  return '<strong>' . t('Origin') . ':</strong> ' . $packager->configuration->url;
}

/**
 * Gets the description of a commit reference
 *
 * @param stdClass $packager
 *  A packager object
 * @param string $sha1
 *  The hash of the commit to check out
 * @return string
 *  The description of the reference
 */
function _dpgit_reference_description($packager, $sha1) {
  $wd = dproject_working_directory_path($packager);
  $log = _dpgit_log($wd . '/.git', 1, $sha1, '.');
  return theme('git_log', $log);
}

function _dpgit_theme_log($log) {
  $out = '<ol class="git-log">';
  foreach ($log as $sha1 => $item) {
    $out .= '<li class="commit">';
    $out .= '<dl class="header">';
    $out .=   '<dt>sha1</dt><dd class="sha1">' . $sha1 . '</dd>';
    foreach ($item['header'] as $name => $value) {
      $out .= '<dt>' . $name . '</dt><dd>' . htmlspecialchars($value) . '</dd>';
    }
    $out .= '</dl>';
    $out .= '<pre class="message">' . htmlspecialchars($item['message']) . '</pre>';
    $out .= '<ul class="files">';
    foreach ($item['files'] as $file => $status) {
      $out .= '<li class="file file-' . strtolower($status) . '">' . 
        '<span class="file-status">' . $status . '</span> ' . 
        '<span class="file-name">' . htmlspecialchars($file) . '</span></li>';
    }
    $out .= '</ul>';
    $out .= '</li>';
  }
  return $out . '</ol>';
}

/**
 * Callback that creates a temporary directory with the
 * files to package.
 *
 * @param stdClass $packager
 *  A packager object
 * @param DProjectRelease $release
 *  A release object
 * @return string
 *  A path to a directory containing the files to package
 */
function _dpgit_package($packager, $release) {
  $repo = dproject_working_directory_path($packager);
  $target = dproject_working_directory_path($packager, $release);

  if (file_exists(dirname($target)) || mkdir(dirname($target), 0777, TRUE)) {
    $out = array();
    $res = _dpgit_checkout($target, $repo . '/.git', $release->metadata->git->sha1, $out);
    if (!$res) {
      dproject_set_packager_message($packager->pid, 'git', 'packaging', 'Failed to pack !sha1 into the directory !dir', array(
        '!sha1' => $release->metadata->git->sha1,
        '!dir' => $target,
      ));
    }
    else {
      return $target;
    }
  }
}

/**
 * Checks out a specific commit of a git repo into a directory
 *
 * @param string $target_dir
 *  The directory to check out the source into
 * @param string $git_dir
 *  The .git directory of the source
 * @param string $sha1
 *  The hash of the commit to check out
 * @param array(string) $out
 *  An array of lines output by git
 * @return bool
 *  Returns TRUE on a successful checkout, FALSE on failure
 */
function _dpgit_checkout($target_dir, $git_dir, $sha1, &$out) {
  // Make sure that the target dir doesn't exist (by killing it if it does)
  if (file_exists($target_dir)) {
    dproject_delete_directory($target_dir);
  }

  $ret = 0;
  exec('git --work-tree="' . $target_dir . '" --git-dir="' . $git_dir . '" checkout ' . $sha1 . ' -- ./', $out, $ret);
  return $ret==0;
}

/**
 * Callback that is used to get tags for
 * a packager source list.
 *
 * @param stdClass $packager
 *  A packager object
 * @return array
 */
function _dpgit_tags_options($packager) {
  $wdir = dproject_working_directory_path($packager);
  $options = array();
  foreach (_dpgit_tags($wdir . '/.git') as $tag) {
    $options['tags/' . $tag] = $tag;
  }
  return $options;
}

/**
 * Callback that is used to get branches for
 * a packager source list.
 *
 * @param stdClass $packager
 *  A packager object
 * @return array
 */
function _dpgit_branches_options($packager) {
  $wdir = dproject_working_directory_path($packager);
  $options = array();
  foreach (_dpgit_branches($wdir . '/.git') as $branch) {
    $options['refs/remotes/' . $branch] = $branch;
  }
  return $options;
}

/**
 * Gets the sha1 hash for a reference
 *
 * @param stdClass $packager
 *  A packager object
 * @param string $reference
 *  The reference (sha1, tag or branch)
 * @return bool
 *  Returns the sha1 hash if the reference was resolved, otherwise FALSE is returned
 */
function _dpgit_ref_sha1($packager, $reference) {
  $wd = dproject_working_directory_path($packager);
  $info = _dpgit_resolve_reference($wd . '/.git', $reference);
  return $info ? $info['sha1'] : FALSE;
}

/**
 * Returns information about a reference
 *
 * @param string $repository
 *  The path to the .git directory
 * @param string $reference
 *  The reference (sha1, tag or branch)
 * @return array
 *  Log entry for the reference
 */
function _dpgit_resolve_reference($repository, $reference) {
  $l = _dpgit_log($repository, 1, $reference);
  foreach ($l as $sha1 => $info) {
    if (!empty($sha1)) {
      $info['sha1'] = $sha1;
      return $info;
    }
    break;
  }
  return FALSE;
}

/**
 * Lists the available (remote) branches in a repository
 *
 * @param string $repository
 *  The path to the .git directory
 *
 * @return array(string) An array with the names of the branches
 **/
function _dpgit_branches($repository) {
  $branches = array();
  $out = shell_exec('git --git-dir="' . $repository . '" branch -r --no-color');

  foreach (split("\n", $out) as $line) {
    if (!empty($line)) {
      $branches[] = trim($line);
    }
  }

  return $branches;
}

/**
 * Lists the available tags in a repository
 *
 * @param string $repository
 *  The path to the .git directory
 *
 * @return array(string) An array with the names of the tags
 **/
function _dpgit_tags($repository) {
  $tags = array();
  $out = shell_exec('git --git-dir="' . $repository . '" tag -l');
  foreach (split("\n", $out) as $line) {
    if (!empty($line)) {
      $tags[] = trim($line);
    }
  }

  return $tags;
}

/**
 * Callback that is used to get the recent commits for
 * a packager source list.
 *
 * @param stdClass $packager
 *  A packager object
 * @return array
 */
function _dpgit_recent_commits($packager) {
  $wdir = dproject_working_directory_path($packager);
  $log = _dpgit_log($wdir . '/.git', 20);

  $recent_commits = array();
  foreach ($log as $sha1 => $info) {
    $time = strtotime($info['header']['date']);
    $recent_commits[$sha1] = format_date($time) . ' - ' . $sha1;
  }

  return $recent_commits;
}

/**
 * Gets the commit log as a associative arrayed keyed to the sha1 of the commit
 *
 * Structure:
 * array(
 *  [sha1] => array(
 *    'header' => array(
 *      'author'  => [name <email>],
 *      'date'    => [iso date-time],
 *    ),
 *    'message' => [commit message],
 *    'files' => array(
 *      [file]  => [status],
 *      ...
 *    )
 *  ),
 *  ...
 * )
 *
 * @param string $repository
 *  The path to the .git directory
 * @param int $commits
 *  The number of log entries to return. Use 0 to get the full log.
 *  Defaults to 10.
 * @param string $sha1
 *  Where to start the log from, defaults to HEAD
 * @param string $file
 *  The path to get the log for (relative to the repository root)
 *  Defaults to '.'
 * @param bool $raw
 *  Set to TRUE to skip parsing and return the raw log
 *
 * @return array
 *  The commit log as a associative arrayed keyed to the sha1 of the commit.
 *  Or the lines in the log in a array if $raw is set to TRUE.
 **/
function _dpgit_log($repository, $commits=10, $sha1='HEAD', $file='.', $raw=FALSE) {
  $out = array();
  $retval = 0;

  // Create a -<n> flag if we should limit the number of log messages to fetch
  $n_flag = '';
  if ($commits) {
    $n_flag = '-' . $commits;
  }

  // We can't use exec as it doesn't preserve trailing whitespace and we need
  // that to differentiate between empty lines in the commit messages and empty
  // lines separating header, commit message and file listing.
  $out = shell_exec('git --git-dir="' . $repository . '" log ' . $n_flag . ' --no-color --date=iso --name-status ' . $sha1 . ' -- .');

  $out = split("\n", $out);

  // Return the raw output if requested
  if ($raw) {
    return $out;
  }

  $log = array();
  $lines = count($out);
  for ($i=0; $i<$lines; $i++) {
    $match = array();
    if (preg_match('/commit ([0-9a-f]+)/', $out[$i], $match)) {
      $sha = $match[1];
    }
    else { // Skip forward if we don't get a sha
      continue;
    }

    $info = array();

    // Parse the header
    $i++;
    $match = array();
    $info['header'] = array();
    while(!empty($out[$i]) && preg_match('/^([^:]+):\s*(.+)$/', $out[$i], $match)) {
      $info['header'][strtolower($match[1])] = $match[2];
      $i++;
    }

    // Extract the commit message
    $i++;
    $message = '';
    while(!empty($out[$i])) {
      $message .= trim($out[$i]) . "\n";
      $i++;
    }
    $info['message'] = $message;

    // Get info about changes
    $i++;
    $files = array();
    while(!empty($out[$i])) {
      $files[substr($out[$i],2)] = substr($out[$i], 0, 1);
      $i++;
    }
    $info['files'] = $files;

    $log[$sha] = $info;
  }

  return $log;
}
