<?php
/**
 * This module provides integration with remote dproject or project servers
 *
 * @version $Id$
 **/

/**
 * Implementation of hook_autoload_info().
 */
function dpremote_autoload_info() {
  return array(
    'DPRemotePackager' => array('file' => 'includes/DPRemotePackager.class.inc'),
  );
}

/**
 * Implementation of hook_dproject_api
 *
 * @return void
 */
function dpremote_dproject_api() {
  return array(
    '1' => array(
      'path' => drupal_get_path('module', 'dpremote') . '/includes',
      'packagers' => array(
        'remote' => array(
          'name' => t('Remote project server'),
          'class' => 'DPRemotePackager',
        ),
      ),
    ),
  );
}