<?php
/**
 * dproject module.
 *
 * @version $Id$
 **/

require_once('dproject.inc');
require_once('dproject.api.inc');
require_once('dproject.token.inc');

/**
 * Implementation of hook_node_info
 *
 * @return array The node types declared by dproject
 **/
function dproject_node_info() {
  return array(
    'dproject' => array(
      'name' => t('Project'),
      'description' => t('A Drupal project, ordinarily a module or theme'),
      'module' => 'dproject',
      'title_label' => t('Name'),
      'body_label' => t('Extra description'),
    ),
  );
}

function dproject_menu() {
  $items = array();

  $items['dproject/ahah/packager_configuration'] = array(
    'page callback' => '_dproject_ahah_packager_configuration',
    'access arguments' => array('access content'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['dproject/ahah/release_source_configuration/%/%'] = array(
    'page callback' => '_dproject_ahah_release_source_configuration',
    'page arguments' => array(4),
    'access callback' => 'node_access',
    'access arguments' => array('update', 3),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%/packagers'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_project_packagers', 1),
    'access callback' => '_dproject_access',
    'access arguments' => array('update', 1),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%/packager/%/delete'] = array(
    'title' => t('Delete project packager'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_delete_project_packager', 1, 3),
    'access callback' => '_dproject_access',
    'access arguments' => array('update', 1),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%/packager/%/package'] = array(
    'title' => t('Package a project release'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_create_project_release', 1, 3),
    'access callback' => '_dproject_access',
    'access arguments' => array('update', 1),
    'type' => MENUITEM_CALLBACK,
  );

  return $items;
}

function _dproject_access($op, $short_name) {
  $node = dproject_get_project_by_name($short_name);
  if ($node) {
    return node_access($op, $node);
  }
  return FALSE;
}

function _dproject_project_packagers($form_state, $short_name) {
  $node = dproject_get_project_by_name($short_name);
  if ($node) {
    drupal_set_title(t('Packagers for !name', array(
      '!name' => $node->title,
    )));

    $packagers = dproject_get_packager_types();
    $pack_options = array(
      '' => t('--Select a packager')
    );
    foreach ($packagers as $name => $def) {
      $pack_options[$name] = $def['title'];
    }

    $pp = dproject_get_project_packagers($node->nid);
    $po = '<ul>';
    foreach ($pp as $p) {
      $po .= '<li><label>' . $p->packager . '</label>';
      $po .= '<div class="packager-description">';
      $po .= dproject_packager_description($p);
      $po .= '</div>';

      $packager_links = array(
        l(t('Package a release'), 'project/' . $short_name . '/packager/' . $p->pid . '/package', array(
          'attributes' => array(
            'class' => 'package',
          ),
        )),
        l(t('Remove'), 'project/' . $short_name . '/packager/' . $p->pid . '/delete', array(
          'attributes' => array(
            'class' => 'delete',
          ),
        )),
      );

      // Add a update link if it's supported by the packager type
      if (isset($packagers[$p->packager]['update callback'])) {
        $packager_links[] = l(t('Update'), 'project/' . $short_name . '/packager/' . $p->pid . '/update', array(
          'attributes' => array(
            'class' => 'update',
          ),
        ));
      }

      $po .= '<ul class="actions">';
      foreach ($packager_links as $link) {
        $po .= '<li>' . $link . '</li>';
      }
      $po .= '</ul>';

      $po .= '</li>';
    }
    $po .= '</ul>';

    $form = array(
      '#submit' => array('_dproject_project_packagers_submit'),
      'packagers' => array(
        '#type' => 'markup',
        '#value' => $po,
      ),
      'project' => array(
        '#type' => 'value',
        '#value' => $node->nid,
      ),
      'packager' => array(
        '#type' => 'select',
        '#title' => t('Add a packager'),
        '#options' => $pack_options,
        '#ahah' => array(
          'path' => 'dproject/ahah/packager_configuration',
          'wrapper' => 'packager-configuration',
        ),
      ),
      'packager_configuration' => array(
        '#type' => 'markup',
        '#value' => '<div id="packager-configuration"></div>',
      ),
    );
    return $form;
  }
  else {
    drupal_not_found();
  }
}

function _dproject_project_packagers_submit($form, $form_state) {
  $values = $form_state['values'];
  $packager_type = $values['packager'];
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager_type]) && isset($packagers[$packager_type]['configuration submit'])) {
    $configuration = call_user_func($packagers[$packager_type]['configuration submit'], $values);
  }
  else {
    $configuration = array();
  }

  $values = array(
    'nid' => $values['project'],
    'packager' => $packager_type,
    'configuration' => json_encode($configuration),
  );
  drupal_write_record('dproject_packager', $values);

  // Call the packager created function for the packager type
  if (isset($packagers[$packager_type]) && isset($packagers[$packager_type]['packager created'])) {
    $pid = db_last_insert_id('dproject_packager', 'pid');
    $packager = dproject_get_project_packager($pid);
    call_user_func($packagers[$packager_type]['packager created'], $packager);
  }
}

function _dproject_create_project_release($form_state, $project_name, $pid) {
  $packager = dproject_get_project_packager($pid);
  $packager_type = dproject_get_packager_types($packager->packager);
  $last_release = dproject_get_latest_release($pid);

  $sources = array(
    '' => t('--Select a source'),
  );
  foreach ($packager_type['sources'] as $name => $def) {
    $sources[$name] = t($def['title']);
  }

  $form['source'] = array(
    '#type' => 'fieldset',
    '#title' => t('Source'),
    'source_name' => array(
      '#type' => 'select',
      '#options' => $sources,
      '#ahah' => array(
        'path' => 'dproject/ahah/release_source_configuration/' . $packager->nid . '/' . $pid,
        'wrapper' => 'source-configuration',
      ),
    ),
    'release_source_configuration' => array(
      '#type' => 'markup',
      '#value' => '<div id="source-configuration"></div>',
    ),
  );

  $form['api_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Api version'),
    '#default_value' => $last_release ? $last_release->api_version : 6,
    '#required' => TRUE,
  );

  $form['major_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Major version'),
    '#default_value' => $last_release ? $last_release->major_version : 1,
    '#required' => TRUE,
  );

  $form['minor_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Minor version'),
    '#default_value' => $last_release ? $last_release->minor_version : 0,
  );

  return $form;
}

function _dproject_ahah_release_source_configuration($pid) {
  $source = $_POST['source_name'];
  $packager = dproject_get_project_packager($pid);
  _dproject_ahah_helper('release_source_configuration', '_dproject_release_configuration_form', $source, $packager);
}

function _dproject_release_configuration_form($source, $packager, $configuration=array()) {
  $ptype = dproject_get_packager_types($packager->packager);
  $def = $ptype['sources'][$source];

  if (isset($def['options callback'])) {
    $options = call_user_func($def['options callback'], $packager);
    return array(
      '#type' => 'select',
      '#options' => $options,
    );
  }
  return array();
}

function _dproject_update_project_packager($project_name, $pid) {
  $p = dproject_get_project_packager($pid);
  $ptype = dproject_get_packager_types($p->packager);
  $node = node_load($p->nid);
  if (isset($ptype['update callback'])) {
    call_user_func($ptype['update callback'], $p);
  }
  drupal_goto('project/' . $node->short_name . '/packagers');
}

function _dproject_delete_project_packager($form_state, $project_name, $pid) {
  $p = dproject_get_project_packager($pid);
  if ($p) {
    $out .= '<p>' . t('Do you really want to delete the !type project packager:', array(
      '!type' => $p->packager,
    )) . '</p>';
    $out .= '<div class="packager-description">' . dproject_packager_description($p) . '</div>';

    return array(
      '#submit' => array('_dproject_delete_project_packager_confirmed'),
      'pid' => array(
        '#type' => 'value',
        '#value' => $p->pid,
      ),
      'confirm_text' => array(
        '#type' => 'markup',
        '#value' => $out,
      ),
      'cancel_link' => array(
        '#type' => 'markup',
        '#value' => l(t('No, cancel this action'), 'node/' . $p->nid),
      ),
      'submit' => array(
        '#type' => 'submit',
        '#value' => t('Yes, go ahead'),
      ),
    );
  }
  else {
    drupal_not_found();
  }
}

function _dproject_delete_project_packager_confirmed($form, $form_state) {
  $pid = $form_state['values']['pid'];
  $p = dproject_get_project_packager($pid);
  if ($p) {
    dproject_delete_project_packager($p);
    $project = node_load($p->nid);
    drupal_goto('project/' . $project->short_name . '/packagers');
  }
  else {
    drupal_not_found();
  }
}

/**
 * Implementation of hook_form
 *
 * @return array The edit or create form for the node
 **/
function dproject_form(&$node, $form_state) {
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => TRUE,
      '#default_value' => $node->title,
      '#weight' => -5,
    );
  }

  $form['short_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Short project name'),
    '#required' => TRUE,
    '#weight' => -4,
    '#default_value' => $node->short_name,
  );

  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Project description'),
    '#required' => TRUE,
    '#weight' => -3,
    '#default_value' => $node->description,
  );

  if ($type->has_body) {
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  if (module_exists('content')) {
    $form['short_name']['#weight'] = content_extra_field_weight('dproject', 'short_name');
    $form['description']['#weight'] = content_extra_field_weight('dproject', 'description');
  }

  return $form;
}

function _dproject_ahah_packager_configuration() {
  $packager = $_POST['packager'];
  _dproject_ahah_helper('packager_configuration', '_dproject_packager_configuration_form', $packager);
}

function _dproject_packager_configuration_form($packager, $configuration=array()) {
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager]) && isset($packagers[$packager]['configuration form'])) {
    $form = array();
    $form['_conf'] = call_user_func($packagers[$packager]['configuration form']);
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Add'),
    );
    return $form;
  }
}

function _dproject_packager_configuration_submit($packager, $configuration=array()) {
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager]) && isset($packagers[$packager]['configuration submit'])) {
    return call_user_func($packagers[$packager]['configuration submit']);
  }
}

/**
 * Helper function for implementing ahah page callbacks
 *
 * @param string $element
 *  The name of the form element, can also be a path like "ahah_config/name_field"
 * @param string $form_callback
 *  The function to call to get the form array
 * @return void
 */
function _dproject_ahah_helper($element, $form_callback/*, $arg1, $arg2 ...*/) {
  $cached_form_state = array();
  $cached_form = form_get_cache($_POST['form_build_id'], $cached_form_state);

  // Resolve the parent of the element that is to be set
  $element_path = split('/', $element);
  $element = $element_path[count($element_path)-1];
  $parent = &$cached_form;
  for ($i=0; $i<count($element_path)-1; $i++) {
    if (isset($parent[$element_path[$i]])) {
      $parent = &$parent[$element_path[$i]];
    }
  }

  $args = func_get_args();
  array_shift($args); // Remove element
  array_shift($args); // Remove callback

  // Check if the callback is callable
  if (is_callable($form_callback)) {
    $set = call_user_func_array($form_callback, $args);
  }

  if (empty($set)) {
    $set = array(
      '#value' => '<span></span>',
    );
  }

  $parent[$element] = $set;
  form_set_cache($_POST['form_build_id'], $cached_form, $cached_form_state);
  $form_state = array('submitted' => FALSE);
  $set = form_builder($form_callback, $set, $form_state);
  $output = drupal_render($set);
  print drupal_to_js(array('status' => TRUE, 'data' => $output));
  exit;
}

/**
 * Implementation of hook_nodeapi
 */
function dproject_nodeapi($node, $op, $form) {
  if ($node->type=='dproject') {
    switch($op) {
      case 'load':
        $res = db_query("SELECT short_name, description FROM {dproject} WHERE nid=%d", array(
          ':nid' => $node->nid,
        ));
        if ($a = db_fetch_array($res)) {
          foreach($a as $name => $val) {
            $node->$name = $val;
          }
        }
      case 'validate':
        if (!preg_match('/^[a-z_0..9]+$/', $node->short_name)) {
          form_set_error('short_name', t('The short name can only contain lowercase letters (a-z), underscores and numbers'), 'error');
        }
        // Check for duplicate names
        $eres = db_query("SELECT COUNT(*) AS name_exists FROM {dproject} WHERE short_name='%s'", array(
          ':short_name' => $node->short_name,
        ));
        if ($eo = db_fetch_object($eres) && $eo->name_exists) {
          form_set_error('short_name', t('The short must be unique'), 'error');
        }

        // TODO: Central server check for duplicate names?
      break;
      case 'delete':
        // Delete all the project packagers
        $packagers = dproject_get_project_packagers($node->nid);
        foreach ($packagers as $packager) {
          dproject_delete_project_packager($packager);
        }

        // Delete releases
        db_query('DELETE FROM {dproject_release} WHERE project_nid=%d', array(
          ':nid' => $node->nid,
        ));

        // Delete all project files
        $proj_dir = dproject_project_file_directory($node->nid);
        if ($proj_dir) {
          dproject_delete_directory($proj_dir);
        }

        // Clean up project information
        db_query('DELETE FROM {dproject} WHERE nid=%d', array(
          ':nid' => $node->nid,
        ));
      break;
      case 'update':
      case 'insert':
        $values = array(
          'nid' => $node->nid,
          'short_name' => $node->short_name,
          'description' => $node->description,
        );
        drupal_write_record('dproject', $values, $op=='update'?'nid':NULL);
        if (module_exists('path') && !module_exists('pathauto')) {
          path_set_alias('node/' . $node->nid, 'project/' . $node->short_name);
        }
      break;
      case 'prepare':

      break;
    }
  }
}
