<?php
/**
 * The main file for the dproject module
 *
 * @version $Id$
 **/

require_once('dproject.api.inc');
require_once('dproject.token.inc');

/**
 * Implementation of hook_node_info
 *
 * @return array The node types declared by dproject
 **/
function dproject_node_info() {
  return array(
    'dproject' => array(
      'name' => t('Project'),
      'description' => t('A Drupal project, ordinarily a module or theme'),
      'module' => 'dproject',
      'title_label' => t('Name'),
      'body_label' => t('Extra description'),
    ),
  );
}

/**
 * Implementation of hook_menu
 **/
function dproject_menu() {
  $items = array();

  $items['dproject/ahah/packager_configuration'] = array(
    'page callback' => '_dproject_ahah_packager_configuration',
    'access arguments' => array('access content'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['dproject/ahah/release_source_configuration/%node/%'] = array(
    'page callback' => '_dproject_ahah_release_source_configuration',
    'page arguments' => array(4),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(3, 'update'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['node/%node/packagers'] = array(
    'title' => 'Packagers',
    'page callback' => '_dproject_packagers_redirect',
    'page arguments' => array(1),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );

  $items['project/%dprojectnode/packagers'] = array(
    'title' => 'Packagers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_project_packagers', 1),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 2,
  );

  $items['project/%dprojectnode/packagers/%/delete'] = array(
    'title' => t('Delete project packager'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_delete_project_packager', 1, 3),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%dprojectnode/packagers/%/update'] = array(
    'title' => t('Update'),
    'page callback' => '_dproject_update_project_packager',
    'page arguments' => array(1, 3),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%dprojectnode/packagers/%/release'] = array(
    'title' => t('Create a project release'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_create_project_release', 1, 3),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%dprojectnode/releases/%'] = array(
    'title' => t('Release information'),
    'page callback' => '_dproject_release_information',
    'page arguments' => array(1, 3),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'view'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%dprojectnode/packagers/%/release/confirm/%'] = array(
    'title' => t('Confirm project release'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_dproject_confirm_project_release', 1, 3, 6),
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'update'),
    'type' => MENUITEM_CALLBACK,
  );

  $items['project/%dprojectnode/release-history/%'] = array(
    'page callback' => '_dproject_feed_generate',
    'page arguments' => array(1, 3),
    'file' => 'dproject.feed.inc',
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'view'),
    'type' => MENUITEM_CALLBACK,
  );
  
  $items['release-history/%dprojectnode/%'] = array(
    'page callback' => '_dproject_feed_generate',
    'page arguments' => array(1, 2),
    'file' => 'dproject.feed.inc',
    'access callback' => '_dproject_node_access',
    'access arguments' => array(1, 'view'),
    'type' => MENUITEM_CALLBACK,
  );

  return $items;
}

/**
 * Menu system wildcard loader for %dprojectnode
 * allowing projects to be referenced by name
 *
 * @param string $short_name 
 * @return stdClass
 */
function dprojectnode_load($short_name) {
  return dproject_get_project_by_name($short_name);
}

/**
 * Helper function used for access callbacks.
 * This function calls and returns the result of
 * the node_access function if the node is of the
 * type dproject. Otherwise FALSE is returned.
 *
 * @param object $node
 *  The node to check for access to
 * @param string $op
 *  The operation that access should be checked for
 * @return bool
 *  TRUE if access is granted, FALSE if not
 */
function _dproject_node_access($node, $op) {
  if (is_object($node) && $node->type=='dproject') {
    return node_access($op, $node);
  }
  return FALSE;
}

function _dproject_packagers_redirect($node) {
  drupal_goto('project/' . $node->short_name . '/packagers/');
  die;
}

function _dproject_project_packagers($form_state, $node) {
  drupal_set_breadcrumb(array(
    l(t('Home'), '<front>'),
    l($node->title, 'node/' . $node->nid),
  ));
  drupal_set_title(t('!title packagers', array(
    '!title' => $node->title,
  )));
  
  $packagers = dproject_get_packager_types();
  $pack_options = array(
    '' => t('--Select a packager')
  );
  foreach ($packagers as $name => $def) {
    $pack_options[$name] = $def['title'];
  }

  $pp = dproject_get_project_packagers($node->nid);
  $po = '<ul>';
  foreach ($pp as $p) {
    $po .= '<li><label>' . $p->packager . '</label>';
    $po .= '<div class="packager-description">';
    $po .= dproject_packager_description($p);
    $po .= '</div>';

    $packager_links = array(
      l(t('Create a release'), 'project/' . $node->short_name . '/packagers/' . $p->pid . '/release', array(
        'attributes' => array(
          'class' => 'package',
        ),
      )),
      l(t('Remove'), 'project/' . $node->short_name . '/packagers/' . $p->pid . '/delete', array(
        'attributes' => array(
          'class' => 'delete',
        ),
      )),
    );

    // Add a update link if it's supported by the packager type
    if (isset($packagers[$p->packager]['update'])) {
      $packager_links[] = l(t('Update'), 'project/' . $node->short_name . '/packagers/' . $p->pid . '/update', array(
        'attributes' => array(
          'class' => 'update',
        ),
      ));
    }

    $po .= '<ul class="actions">';
    foreach ($packager_links as $link) {
      $po .= '<li>' . $link . '</li>';
    }
    $po .= '</ul>';

    $po .= '</li>';
  }
  $po .= '</ul>';

  $form = array(
    '#submit' => array('_dproject_project_packagers_submit'),
    '#validate' => array('_dproject_project_packagers_validate'),
    'packagers' => array(
      '#type' => 'markup',
      '#value' => $po,
    ),
    'project' => array(
      '#type' => 'value',
      '#value' => $node->nid,
    ),
    'packager' => array(
      '#type' => 'select',
      '#title' => t('Add a packager'),
      '#options' => $pack_options,
      '#ahah' => array(
        'path' => 'dproject/ahah/packager_configuration',
        'wrapper' => 'packager-configuration',
      ),
    ),
    'packager_configuration' => array(
      '#type' => 'markup',
      '#value' => '<div id="packager-configuration"></div>',
    ),
  );
  return $form;
}

function _dproject_project_packagers_validate($form, $form_state) {
  $values = $form_state['values'];
  $packager_type = $values['packager'];
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager_type]) && isset($packagers[$packager_type]['configuration validate'])) {
    call_user_func($packagers[$packager_type]['configuration validate'], $values);
  }
}

function _dproject_project_packagers_submit($form, $form_state) {
  $values = $form_state['values'];
  $packager_type = $values['packager'];
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager_type]) && isset($packagers[$packager_type]['configuration submit'])) {
    $configuration = call_user_func($packagers[$packager_type]['configuration submit'], $values);
  }
  else {
    $configuration = array();
  }

  $values = array(
    'nid' => $values['project'],
    'packager' => $packager_type,
    'configuration' => json_encode($configuration),
  );
  drupal_write_record('dproject_packager', $values);

  // Call the packager's created function for the packager type
  if (isset($packagers[$packager_type]) && isset($packagers[$packager_type]['packager created'])) {
    $pid = db_last_insert_id('dproject_packager', 'pid');
    $packager = dproject_get_project_packager($pid);
    call_user_func($packagers[$packager_type]['packager created'], $packager);
  }
}

function _dproject_create_project_release($form_state, $project, $pid) {
  $packager = dproject_get_project_packager($pid);
  $packager_type = dproject_get_packager_types($packager->packager);
  $last_release = dproject_get_latest_release($pid);

  drupal_set_title(t('Create a release of !name', array('!name' => $project->title)));
  drupal_set_breadcrumb(array(
    l(t('Home'), '<front>'),
    l($project->title, 'node/' . $project->nid),
    l('Packagers', 'project/' . $project->short_name . '/packagers'),
  ));

  // Allow packagers to provide completely customized forms
  if (isset($packager_type['custom_creation_form']) && is_callable($packager_type['custom_creation_form'])) {
    return call_user_func($packager_type['custom_creation_form'], 
      $form_state, $project, $packager, $packager_type, $last_release);
  }

  $form = array(
    '#id' => 'dproject_create_project_release',
  );

  $form['pid'] = array(
    '#type' => 'value',
    '#value' => $pid,
  );

  $sources = array(
    '' => t('--Select a source'),
  );
  foreach ($packager_type['sources'] as $name => $def) {
    $sources[$name] = t($def['title']);
  }

  $form['source'] = array(
    '#type' => 'fieldset',
    '#title' => t('Source'),
    'source_name' => array(
      '#type' => 'select',
      '#options' => $sources,
      '#ahah' => array(
        'path' => 'dproject/ahah/release_source_configuration/' . $packager->nid . '/' . $pid,
        'wrapper' => 'source-configuration',
      ),
    ),
    'release_source_configuration' => array(
      '#type' => 'markup',
      '#value' => '<div id="source-configuration"></div>',
    ),
  );

  $version = FALSE;
  if ($last_release) {
    $version = $last_release->get_version();
  }
  
  $form['api_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Api version'),
    '#default_value' => $version ? $version[0] : 6,
    '#required' => TRUE,
  );

  $form['major_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Major version'),
    '#default_value' => $version ? $version[1] : 1,
    '#required' => TRUE,
  );

  $form['minor_version'] = array(
    '#type' => 'textfield',
    '#title' => t('Minor version'),
    '#default_value' => $version ? $version[2] : 0,
    '#required' => TRUE,
  );

  $form['version_extra'] = array(
    '#type' => 'textfield',
    '#title' => t('Version extra'),
    '#default_value' => $version ? $version[3] : '',
  );

  $form['release_type'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Release type'),
    '#options' => dproject_release_types(TRUE),
    '#required' => TRUE,
  );

  $status_options = array(
    'unsupported' => t('Unsupported'),
    'supported' => t('Supported'),
    'excl_supported' => t('Exclusively supported'),
    'recommended' => t('Recommended'),
    'excl_recommended' => t('Recommended and exclusively supported'),
  );
  
  $form['release_status'] = array(
    '#type' => 'select',
    '#title' => t('Release status'),
    '#options' => $status_options,
  );

  $form['#validate'] = array('_dproject_create_project_release_validate');
  $form['#submit'] = array('_dproject_create_project_release_submit');
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Create'),
  );

  // Allow the packager to alter the form
  if (isset($packager_type['create_release_form_alter']) && is_callable($packager_type['create_release_form_alter'])) {
    call_user_func_array($packager_type['create_release_form_alter'], array(&$form, $form_state, $form['#id'], $project, $packager, $packager_type, $last_release));
  }

  return $form;
}

/**
 * Helper function used to check if
 * a value can be treated as a int
 *
 * @param mixed $v
 *  A value that should be checked
 * @return bool
 *  Returns TRUE if the value can be treated as a int
 */
function _dproject_is_int($v) {
  if (is_numeric($v) && intval($v)==$v) {
    return TRUE;
  }
}

/**
 * Validates the release creation form
 *
 * @param array $form
 *  The form array
 * @param array $form_state
 *  The form state
 * @return void
 */
function _dproject_create_project_release_validate($form, $form_state) {
  $values = $form_state['values'];

  $packager = dproject_get_project_packager($values['pid']);
  $packager_type = dproject_get_packager_types($packager->packager);

  // Validate the versions that always have to be integers
  $nv = array(
    'api_version' => t('Api version'),
    'major_version' => t('Major version'),
  );
  foreach ($nv as $field => $title) {
    if (!is_numeric($values[$field])) {
      form_set_error($field, t('The !title must be a number', array(
        '!title' => $title,
      )));
    }
  }

  // Validate the minor version number
  if (!_dproject_is_int($values['minor_version']) || $values['minor_version']<0) {
    if ($values['version_extra'] != 'dev') {
      form_set_error('version_extra', 'You must create a "dev" release if you don\'t provide a numeric minor version number equal to or greater than zero');
    }
    else if ($values['minor_version']!='x') {
      drupal_set_message('Warning! The non-numeric or negative minor version number for this dev-release is interpreted as unspecified and will be replaced by an x', 'warning');
    }
  }

  // Warn when creating a dev release with a specified minor version
  if ($values['version_extra'] == 'dev' && _dproject_is_int($values['minor_version'])) {
    drupal_set_message('Warning! You are creating a dev release so the minor version number for this release will be set as unspecified and replaced by an x', 'warning');
  }

  // Validate the version extra format
  if (!empty($values['version_extra']) && !preg_match('/^[_a-z0-9]+$/', $values['version_extra'])) {
    form_set_error('version_extra', t('The version extra field can only contain lower-case letters, numbers and underscores'));
  }

  if (empty($values['source_identifier'])) {
    form_set_error('source_name', t('You have to select a valid source for the release'));
  }
  else {
    $source = $packager_type['sources'][$values['source_name']];
    if (isset($source['resolve'])) {
      $res = call_user_func_array($source['resolve'], array($packager, $values['source_identifier']));
      if ($res === FALSE) {
        form_set_error('source_identifier', t('The selected source is not valid'));
      }
    }
  }
}

/**
 * Handles submission of the release creation form
 * and redirects to the confirmation page
 *
 * @param array $form
 *  The form array
 * @param array $form_state
 *  The form state
 * @return void
 */
function _dproject_create_project_release_submit($form, $form_state) {
  $values = $form_state['values'];
  $packager = dproject_get_project_packager($values['pid']);
  $packager_type = dproject_get_packager_types($packager->packager);
  $project = node_load($packager->nid);
  $rel = new DProjectRelease($project);
  $metadata = $rel->get_metadata_object();

  // Make changes in minor version number when necessary
  if ($values['version_extra'] == 'dev' || !_dproject_is_int($values['minor_version']) || $values['minor_version']<0) {
    $values['minor_version'] = NULL;
  }

  // Set version so that we can get the version string
  $rel->set_version($values['api_version'], $values['major_version'], $values['minor_version'], $values['version_extra']);

  // Set the packager for the release and store its configuration
  $rel->set_packager($packager->pid);
  if (isset($packager_type['configure release'])) {
    call_user_func_array($packager_type['configure release'], array(
      &$rel, $packager, $values['source_identifier'],
    ));
  }

  // Set release type information
  $release_type = array();
  foreach ($values['release_type'] as $type) {
    if ($type) {
      $release_type[] = $type;
    }
  }
  $metadata->terms = $release_type;
  
  // Check if this new release is exclusively supported
  if (substr($values['release_status'], 0, 5)=='excl_') {
    $metadata->exclusively_supported = TRUE;
    $values['release_status'] = substr($values['release_status'], 5);
  }
  
  // Interpret the release status value
  $status = $rel->get_status();
  switch ($values['release_status']) {
    case 'unsupported': 
      $status = DPROJECT_RELEASE_STATUS_UNSUPPORTED;
    break;
    case 'supported':
      $status = DPROJECT_RELEASE_STATUS_SUPPORTED;
    break;
    case 'recommended':
      $status = DPROJECT_RELEASE_STATUS_RECOMMENDED;
    break;
  }

  // Set release state and save it
  $rel->set_status($status);
  $rel->set_published(FALSE);
  $rel->set_temporary(TRUE);
  $rel->save();

  $rid = $rel->get_id();

  // Send the user to the confirmation page
  drupal_goto("project/{$project->short_name}/packagers/{$packager->pid}/release/confirm/{$rid}");
}

/**
 * Displays a release confirmation page
 *
 * @param array $form
 *  The form array
 * @param array $form_state
 *  The form state
 * @param string $pid
 *  The id of the used packager
 * @param string $rid
 *  The if of the release
 * @return void
 */
function _dproject_confirm_project_release($form_state, $project, $pid, $rid) {
  drupal_add_css(drupal_get_path('module','dproject') . '/css/admin.css');

  $rel = DProjectRelease::load($rid);
  $packager = dproject_get_project_packager($rel->get_packager());
  $packager_type = dproject_get_packager_types($packager->packager);
  $source = $packager_type['sources'][$values['source_name']];

  drupal_set_title(t('Confirm release settings for !name', array('!name' => $project->title)));

  $metadata = $rel->get_metadata_object();
  $version = $rel->get_version();

  // Fill an array with the human readable names
  // of the selected release types
  $rt = array();
  $release_types = dproject_release_types(TRUE);
  foreach ($metadata->terms as $term) {
    if (isset($release_types[$term])) {
      $rt[] = $release_types[$term];
    }
  }
  
  switch ($rel->get_status()) {
    case DPROJECT_RELEASE_STATUS_UNSUPPORTED:
      $status = t('Unsupported');
    break;
    case DPROJECT_RELEASE_STATUS_SUPPORTED:
      $status = t('Supported');
    break;
    case DPROJECT_RELEASE_STATUS_RECOMMENDED:
      $status = t('Recommended');
    break;
  }

  $form = array(
    '#id' => 'dproject-confirm-release-configuration-form',
    '#submit' => array('_dproject_project_release_create'),
    'release' => array(
      '#type' => 'value',
      '#value' => $rel->get_id(),
    ),
    'intro_text' => array(
      '#value' => '<p>' . t('Please confirm that the release version is correct and that the source is properly configured before creating the release') . '</p>',
      '#weight' => -10,
    ),
    'version' => array(
      '#type' => 'item',
      '#title' => t('Version'),
      '#value' => $rel->version_string(),
      '#weight' => -8,
    ),
    'release_status' => array(
      '#type' => 'item',
      '#title' => t('Release status'),
      '#value' => $status,
      '#weight' => -8,
    ),
    'release_type' => array(
      '#type' => 'item',
      '#title' => t('Release type'),
      '#value' => join($rt, '<br/>'),
      '#weight' => -8,
    ),
    'packager_description' => array(
      '#type' => 'item',
      '#title' => t('Packager (@name)', array('@name' => $packager->packager)),
      '#value' => dproject_packager_description($packager),
      '#weight' => -5,
    ),
    'source_description' => array(
      '#type' => 'item',
      '#title' => t('Source description'),
      '#value' => dproject_release_source_description($rel),
      '#weight' => -5,
    ),
    // TODO: The cancel link should be rewired to a middle step that deletes the
    // temporary release entry, minimizing the cleanup work that cron has to do.
    'cancel_link' => array(
      '#type' => 'markup',
      '#value' => l(t('Cancel'), 'node/' . $project->nid),
    ),
    'submit' => array(
      '#type' => 'submit',
      '#value' => t('Create release'),
      '#weight' => 10,
    ),
  );
  
  if (isset($metadata->exclusively_supported) && $metadata->exclusively_supported) {
    $form['exclusive'] = array(
      '#type' => 'item',
      '#title' => t('Exclusivity'),
      '#value' => t('This release has been marked as exclusively supported. All releases for Drupal !api_version with a lower version number will therefore be marked as unsupported.', array(
        '!api_version' => $version[0],
      )),
      '#weight' => -7,
    );
  }
  
  return $form;
}

function _dproject_project_release_create($form, $form_state) {
  $release = DProjectRelease::load($form_state['values']['release']);

  $release->package();
  $release->set_published(TRUE);
  $release->set_temporary(FALSE);
  $release->save();
  
  $metadata = $release->get_metadata_object();
  $v = $release->get_version();
  // Set preceding releases with the same api-version as unsupported
  // if this release should be exclusively supported.
  if (isset($metadata->exclusively_supported) && $metadata->exclusively_supported) {
    // The reason that we get the id's of the releases that should be marked
    // as unsupported instead of directly updating the table is that we want to make all
    // changes through the api. This opens up for adding stuff like a audit trail later.
    $res = db_query("SELECT rid FROM {dproject_release}
      WHERE api_version=%d
      AND rid!=%d
      AND status!=%d", array(
        ':api' => $v[0],
        ':rid' => $release->get_id(),
        ':status' => DPROJECT_RELEASE_STATUS_UNSUPPORTED,
    ));
    while ($urid = db_result($res)) {
      dproject_change_release_status($urid, DPROJECT_RELEASE_STATUS_UNSUPPORTED);
    }
  }
  // Make sure that only one release for this api version is marked as recommended.
  // If the release was marked as exclusively supported this has already been taken
  // care of.
  else if ($release->get_status()==DPROJECT_RELEASE_STATUS_RECOMMENDED) {
    $res = db_query("SELECT rid FROM {dproject_release}
      WHERE api_version=%d
      AND rid!=%d
      AND status=%d", array(
        ':api' => $v[0],
        ':rid' => $release->get_id(),
        ':status' => DPROJECT_RELEASE_STATUS_RECOMMENDED,
    ));
    while ($urid = db_result($res)) {
      dproject_change_release_status($urid, DPROJECT_RELEASE_STATUS_SUPPORTED);
    }
  }

  $node = $release->get_project_node();
  drupal_goto('node/' . $node->nid);
}

function _dproject_ahah_release_source_configuration($pid) {
  $source = $_POST['source_name'];
  $packager = dproject_get_project_packager($pid);
  _dproject_ahah_helper('source/release_source_configuration', '_dproject_release_configuration_form', $source, $packager);
}

function _dproject_release_configuration_form($source, $packager, $configuration=array()) {
  $ptype = dproject_get_packager_types($packager->packager);
  $def = $ptype['sources'][$source];

  if (isset($def['options'])) {
    $options = call_user_func($def['options'], $packager);
    return array(
      'source_identifier' => array(
        '#type' => 'select',
        '#options' => $options,
      ),
    );
  }
  return array();
}

function _dproject_update_project_packager($node, $pid) {
  $p = dproject_get_project_packager($pid);
  $ptype = dproject_get_packager_types($p->packager);
  if (isset($ptype['update'])) {
    call_user_func($ptype['update'], $p);
  }
  drupal_goto('project/' . $node->short_name . '/packagers');
}

function _dproject_delete_project_packager($form_state, $node, $pid) {
  $p = dproject_get_project_packager($pid);
  if ($p) {
    $out .= '<p>' . t('Do you really want to delete the !type project packager for @project:', array(
      '!type' => $p->packager,
      '@project' => $node->title,
    )) . '</p>';
    $out .= '<div class="packager-description">' . dproject_packager_description($p) . '</div>';

    return array(
      '#submit' => array('_dproject_delete_project_packager_confirmed'),
      'pid' => array(
        '#type' => 'value',
        '#value' => $p->pid,
      ),
      'confirm_text' => array(
        '#type' => 'markup',
        '#value' => $out,
      ),
      'cancel_link' => array(
        '#type' => 'markup',
        '#value' => l(t('No, cancel this action'), 'project/' . $node->short_name . '/packagers'),
      ),
      'submit' => array(
        '#type' => 'submit',
        '#value' => t('Yes, go ahead'),
      ),
    );
  }
  else {
    drupal_not_found();
  }
}

function _dproject_delete_project_packager_confirmed($form, $form_state) {
  $pid = $form_state['values']['pid'];
  $p = dproject_get_project_packager($pid);
  if ($p) {
    dproject_delete_project_packager($p);
    $node = node_load($p->nid);
    drupal_goto('project/' . $node->short_name . '/packagers');
  }
  else {
    drupal_not_found();
  }
}

/**
 * Implementation of hook_form
 *
 * @return array The edit or create form for the node
 **/
function dproject_form(&$node, $form_state) {
  $type = node_get_types('type', $node);

  if ($type->has_title) {
    $form['title'] = array(
      '#type' => 'textfield',
      '#title' => check_plain($type->title_label),
      '#required' => TRUE,
      '#default_value' => $node->title,
      '#weight' => -5,
    );
  }

  $form['short_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Short project name'),
    '#required' => TRUE,
    '#weight' => -4,
    '#default_value' => $node->short_name,
  );

  $form['description'] = array(
    '#type' => 'textarea',
    '#title' => t('Project description'),
    '#required' => TRUE,
    '#weight' => -3,
    '#default_value' => $node->description,
  );

  if ($type->has_body) {
    $form['body_field'] = node_body_field($node, $type->body_label, $type->min_word_count);
  }

  if (module_exists('content')) {
    $form['short_name']['#weight'] = content_extra_field_weight('dproject', 'short_name');
    $form['description']['#weight'] = content_extra_field_weight('dproject', 'description');
  }

  return $form;
}

function _dproject_ahah_packager_configuration() {
  $packager = $_POST['packager'];
  _dproject_ahah_helper('packager_configuration', '_dproject_packager_configuration_form', $packager);
}

function _dproject_packager_configuration_form($packager, $configuration=array()) {
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager]) && isset($packagers[$packager]['configuration form'])) {
    $form = array();
    $form['_conf'] = call_user_func($packagers[$packager]['configuration form']);
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Add'),
    );
    return $form;
  }
}

function _dproject_packager_configuration_submit($packager, $configuration=array()) {
  $packagers = dproject_get_packager_types();
  if (isset($packagers[$packager]) && isset($packagers[$packager]['configuration submit'])) {
    return call_user_func($packagers[$packager]['configuration submit']);
  }
}

/**
 * Helper function for implementing ahah page callbacks
 *
 * @param string $element
 *  The name of the form element, can also be a path like "ahah_config/name_field"
 * @param string $form_callback
 *  The function to call to get the form array
 * @return void
 */
function _dproject_ahah_helper($element, $form_callback/*, $arg1, $arg2 ...*/) {
  $cached_form_state = array();
  $cached_form = form_get_cache($_POST['form_build_id'], $cached_form_state);

  // Resolve the parent of the element that is to be set
  $element_path = split('/', $element);
  $element = $element_path[count($element_path)-1];
  $parent = &$cached_form;
  for ($i=0; $i<count($element_path)-1; $i++) {
    if (isset($parent[$element_path[$i]])) {
      $parent = &$parent[$element_path[$i]];
    }
  }

  $args = func_get_args();
  array_shift($args); // Remove element
  array_shift($args); // Remove callback

  // Check if the callback is callable
  if (is_callable($form_callback)) {
    $set = call_user_func_array($form_callback, $args);
  }

  if (empty($set)) {
    $set = array(
      '#value' => '<span></span>',
    );
  }

  $parent[$element] = $set;
  form_set_cache($_POST['form_build_id'], $cached_form, $cached_form_state);
  $form_state = array('submitted' => FALSE);
  $set = form_builder($form_callback, $set, $form_state);
  $output = drupal_render($set);
  print drupal_to_js(array('status' => TRUE, 'data' => $output));
  exit;
}

/**
 * Implementation of hook_nodeapi
 */
function dproject_nodeapi($node, $op, $form) {
  if ($node->type=='dproject') {
    switch($op) {
      case 'load':
        $res = db_query("SELECT short_name, description FROM {dproject} WHERE nid=%d", array(
          ':nid' => $node->nid,
        ));
        if ($a = db_fetch_array($res)) {
          foreach($a as $name => $val) {
            $node->$name = $val;
          }
        }
      case 'validate':
        if (!preg_match('/^[a-z_0..9]+$/', $node->short_name)) {
          form_set_error('short_name', t('The short name can only contain lowercase letters (a-z), underscores and numbers'), 'error');
        }
        // Check for duplicate names
        $eres = db_query("SELECT COUNT(*) AS name_exists FROM {dproject} WHERE short_name='%s'", array(
          ':short_name' => $node->short_name,
        ));
        if ($eo = db_fetch_object($eres) && $eo->name_exists) {
          form_set_error('short_name', t('The short must be unique'), 'error');
        }

        // TODO: Central server check for duplicate names?
      break;
      case 'delete':
        // Delete all the project packagers
        $packagers = dproject_get_project_packagers($node->nid);
        foreach ($packagers as $packager) {
          dproject_delete_project_packager($packager);
        }

        // Delete releases
        db_query('DELETE FROM {dproject_release} WHERE project_nid=%d', array(
          ':nid' => $node->nid,
        ));

        // Delete all project files
        $proj_dir = dproject_project_file_directory($node->nid);
        if ($proj_dir) {
          dproject_delete_directory($proj_dir);
        }

        // Clean up project information
        db_query('DELETE FROM {dproject} WHERE nid=%d', array(
          ':nid' => $node->nid,
        ));
      break;
      case 'update':
      case 'insert':
        $values = array(
          'nid' => $node->nid,
          'short_name' => $node->short_name,
          'description' => $node->description,
        );
        drupal_write_record('dproject', $values, $op=='update'?'nid':NULL);
        if (module_exists('path') && !module_exists('pathauto')) {
          path_set_alias('node/' . $node->nid, 'project/' . $node->short_name);
        }
      break;
      case 'prepare':

      break;
    }
  }
}

function _dproject_append_packager_info(&$release, $path_info, &$content) {
  if ($path_info['extension']=='info') {
    $version = $release->get_version();
    $node = $release->get_project_node();
    
    $packaging_info = array();
    $packaging_info[] = '; Information added by ' . variable_get('site_name','unknown') . ' packaging script on ' . date('c', $release->get_created());
    $packaging_info[] = 'version = "' . $release->version_string() . '"';
    $packaging_info[] = 'core = "' . $version[0] . '.x"';
    $packaging_info[] = 'project = "' . $node->short_name . '"';
    $packaging_info[] = 'datestamp = "' . $release->get_created() . '"';
    $packaging_info[] = 'project status url = "' . url('release-history', array('absolute'=>TRUE)) . '"';
    $content .= "\n\n" . join("\n", $packaging_info);
  }
}

/**
 * Implementation of hook_views_api().
 */
function dproject_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'dproject') . '/views',
  );
}